<body>
	<div class="flex_containerTit">
    	<p>Página principal</p>
    	<p>URL: file:///Practica%205/index.html</p>
    </div>
    	
    
	<header>
		<a href="index.php"><h1>Myst</h1></a>
	</header>
<!--
	<nav>
		<a href="index.html"><span class="icon-menu"></span>Menú</a>
        <a href="index.html"><span class="icon-home"></span>Inicio</a>
        <a href="formulario_busqueda.html"><span class="icon-search-circled"></span>Buscar</a>
        <a href="registro.html"><span class="icon-doc-text-inv"></span>Registrarse</a>
        <a href="usuario_registrado.html"><span class="icon-user"></span>Mi perfil</a>
	</nav>
	-->

	<input type="checkbox" id="activador">
    <nav>
        <ul>
            <li><label for="activador">&equiv;</label></li>
            <li><a href="index.php"><span class="icon-home" aria-hidden="true"></span><span>Inicio</span></a></li>
            <li><a href="formulario_busqueda.php"><span class="icon-search-circled" aria-hidden="true"></span><span>Buscar</span></a></li>
            <!--<li><a href="registro.php"><span class="icon-doc-text-inv" aria-hidden="true"></span><span>Registro</span></a></li>-->
            <li><a href="usuario_registrado.php"><span class="icon-user" aria-hidden="true"></span><span>Mi perfil</span></a></li>
            <li><a href="index.php"><span class="icon-user" aria-hidden="true"></span><span>Logout</span></a></li>
        </ul>
    </nav>
</body>