<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!--Css generales-->
	<link rel="stylesheet" href="css/fontello.css">
	<link href="https://fonts.googleapis.com/css?family=Rajdhani|Satisfy" rel="stylesheet">

	<link rel="alternate stylesheet" type="text/css" href="./Responsive_css/responsive_header_nav_footer.css" title="Responsive">

	<link rel="alternate stylesheet" type="text/css" href="./Accesible_css/accesible_header_nav_footer.css" title="Accesible">

	
</head>